deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
plugins:
  - opentelemetry
plugin_attr:
  opentelemetry:
    resource:
      service.name: APISIX[front]
    collector:
      address: jaeger:4318
