source 'https://rubygems.org'

gem 'sinatra'
gem 'rackup'
gem 'pg'
gem 'sequel'
gem 'sinatra-contrib'
gem 'logger'
gem 'puma'

gem 'opentelemetry-sdk'
gem 'opentelemetry-instrumentation-all'
gem 'opentelemetry-exporter-otlp'
gem 'google-protobuf', :platforms => :ruby
