{{- with .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing
  namespace: {{ $.Release.Namespace }}
  labels:
    type: app
    app: pricing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing
  template:
    metadata:
      labels:
        type: app
        app: pricing
    spec:
      containers:
        - name: pricing
          image: {{ .apps.pricing.image }}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
            - name: FLASK_SQLALCHEMY_DATABASE_URI
              value: postgresql://$(DB_USERNAME):$(DB_PASSWORD)@postgres:5432/postgres?options=-c%20search_path=pricing
            - name: FLASK_SQLALCHEMY_TRACK_MODIFICATIONS
              value: "False"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://collector:4317
            - name: OTEL_SERVICE_NAME
              value: pricing
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
---
apiVersion: v1
kind: Service
metadata:
  name: pricing
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: pricing
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pricing
  namespace: {{ $.Release.Namespace }}
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - http:
        paths:
          - path: /prices
            pathType: Prefix
            backend:
              service:
                name: pricing
                port:
                  number: 8000
{{- end }}
