{{- with .Values }}
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ "postgres" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ "root" | b64enc | quote }}
{{- end }}
