{{- with .Values }}
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ include "otel.namespace" . }}
type: Opaque
data:
  POSTGRES_USER: {{ .services.database.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .services.database.password | b64enc | quote }}
{{- end }}
