{{- with .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .apps.warehouses.uk.name }}
  namespace: {{ include "otel.namespace" . }}
  labels:
    type: app
    location: eu
    app: {{ .apps.warehouses.uk.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .apps.warehouses.uk.name }}
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        type: app
        location: eu
        app: {{ .apps.warehouses.uk.name }}
    spec:
      containers:
        - name: warehouse-us
          image: {{ .apps.warehouses.uk.image }}
          env:
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: postgresql
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://{{ .global.services.database.host }}:{{ .global.services.database.port }}/{{ .global.services.database.dbname }}?currentSchema=warehouse_uk
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_USER
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
            - name: QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://{{ .global.services.collector.host }}:{{ .global.services.collector.ports.grpc }}"
            - name: QUARKUS_OTEL_SERVICE_NAME
              value: stocks UK
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .apps.warehouses.uk.host }}
  namespace: {{ include "otel.namespace" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .apps.warehouses.uk.port }}
  selector:
    app: {{ .apps.warehouses.uk.name }}
{{- end }}
