opentelemetry-collector:
  image:
    repository: "otel/opentelemetry-collector-k8s"
    tag: "0.123.0"
  fullnameOverride: collector
  enabled: true
  mode: deployment
  presets:
    kubernetesAttributes:
      enabled: true
  serviceAccount:
    create: false
  ports:
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false
  config:
    processors:
      batch: {}
      resource:
        attributes:
          - key: k8s.cluster.name
            value: otel-demo
            action: upsert
    exporters:
      debug:
        sampling_initial: 1
        sampling_thereafter: 50
      otlp:
        endpoint: jaeger-collector:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: ["otlp"]
          processors: ["batch", "resource"]
          exporters: ["otlp"]

traefik:
  fullnameOverride: traefik
  deployment:
    replicas: 1
  gateway:
    enabled: false
  rbac:
    enabled: true
  ports:
    web:
      nodePort: 30080
  tracing:
    otlp:
      enabled: true
      grpc:
        enabled: true
        endpoint: collector:4317
        insecure: true

valkey:
  architecture: standalone
  fullnameOverride: valkey
  auth:
    enabled: false
  primary:
    kind: Deployment
    persistence:
      enabled: false

jaeger:
  fullnameOverride: jaeger
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false
