networking:
  replicateServices:
    fromHost:
      - from: otel/redis-master
        to: default/cache
      - from: otel/jaeger
        to: default/tracing
      - from: otel/traefik
        to: default/ingress
      - from: otel/mosquitto
        to: default/messages
sync:
  toHost:
    ingresses:
      enabled: true
