{{- with .Values }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog
  namespace: {{ $.Release.Namespace }}
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
          - path: /search
            pathType: Prefix
            backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
{{- end }}
