{{- with .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: {{ include "otel.namespace" . }}
  labels:
    type: infra
    observability: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      observability: jaeger
  template:
    metadata:
      labels:
        type: infra
        observability: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.60
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: {{ include "otel.namespace" . }}
spec:
  type: NodePort
  ports:
    - name: frontend
      port: 16686
      nodePort: 31686
    - name: otel-grpc
      port: 4317
    - name: otel-http
      port: 4318
  selector:
    observability: jaeger
{{- end }}
